Hotfix/0.18.1
jac-uk/assessments pull request #144
Opened 2022-03-02 19:48 UTC by tomlovesgithub

**Author checklist**

- [ ] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [ ] Fill in the details below and delete as appropriate
- [ ] Be proactive in getting your work approved 💪

PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-03-15 09:59 UTC, HalcyonJAC commented on package.json
> +    "deploy-service-offline:develop": "rm -rf dist; mkdir dist; cp service-offline/index.html dist/index.html; firebase deploy --only hosting:develop-assessments-app -P develop",
This deployment script doesn't work on Windows so I couldn't test the deployment

2022-04-05 16:19 UTC, warrensearle requested changes
One teeny tiny change 😄

2022-04-05 16:19 UTC, warrensearle commented on package.json
> +    "deploy-service-offline:develop": "rm -rf dist; mkdir dist; cp service-offline/index.html dist/index.html; firebase deploy --only hosting:develop-assessments-app -P develop",
Could you amend script name to follow the pattern `environment:command` as that's what we've adopted elsewhere
e.g. `develop:deploy-service-offline` instead of `deploy-service-offline:develop`

2022-08-05 16:14 UTC, HalcyonJAC approved these changes

2022-10-13 19:13 UTC, andrew-isaac requested changes
@warrensearle  - Is this work still needed by @tomlovesgithub  it has been open a while now?

2022-12-01 20:21 UTC, warrensearle approved these changes

2022-12-02 12:55 UTC, warrensearle commented
@tomlovesgithub we worked on this a long time ago, late one night...

Please could you double-check whether the changes in this PR are good and have made it into `main`? 

I know we created a couple of branches with the same changes in (can't remember why!) so this may well be able to be deleted.

2023-01-11 17:25 UTC, closed without merging